---JOIN--- 

--실습 1 
SELECT A.EMP_ID
     , A.NAME 
     , B.DEPT_NAME
  FROM EMP A
    , DEPT B
WHERE A.DEPT_NO = B.DEPT_NO 
 AND A.RETIRE_YN = 'Y' ; 
 
 --실습 2 
 SELECT A.PRODUCT_NAME
        , A.PRICE
        , B.REVIEW_ID
        , B.RATING
        , B.REVIEW_TEXT 
   FROM LG_PRODUCT A
   , PRODUCT_REVIEW B 
WHERE A.PRODUCT_ID = B.PRODUCT_ID 
 AND B.PRODUCT_ID = 'P003' ;
 
 
--실습 3 
SELECT A.MEMBER_NAME
        , D.PRODUCT_NAME
  FROM LG_MEMBER A
        , LG_MEMBER_DEVICE B 
        , LG_DEVICE C 
        , LG_PRODUCT D 
WHERE A.MEMBER_ID = B.MEMBER_ID
 AND B.MEMBER_ID = 'MEMBER06' 
 AND B.ACTIVE_FLAG = 'Y' 
 AND B.DEVICE_ID = C.DEVICE_ID 
 AND C.PRODUCT_ID = D.PRODUCT_ID ;
 
 --INNER JOIN / OUTER JOIN 
 SELECT *
  FROM 회원 A
     , 회원연락처 B 
 WHERE A.회원ID = B.회원ID ; 
 
 SELECT * 
  FROM 회원 A 
    , 회원연락처 B
WHERE A.회원ID 

SELECT DISTINCT MEMBER_ID
  FROM LG_MEMBER_DEVICE ; 
  
SELECT MEMBER_ID, COUNT(*) AS 회원별디바이스수 
  FROM LG_MEMBER A 
    , LG_MEMBER_DEVICE B
WHERE A.MEMBER_ID = B.MEMBER_ID ; 

SELECT * 
  FROM 회원 A 
    , 회원연락처 B
WHERE A.회원ID = B.회원ID(+)
  AND B.회원ID IS NULL 

--실습 1
SELECT A.MEMBER_NAME
    , A.BIRTH_YEAR
    , A.CITY_NAME
    , B.DEVICE_ID 
    , B.ASSIGED_FROM 
 FROM LG_MEMBER A
    , LG_MEMBER_DEVICE B
WHERE A.MEMBER_ID = B.MEMBER_ID


--실습 4 
SELECT DISTINCT MEMBER_ID 
  FROM LG_DEVICE_STATE_LOG 
  
SELECT MEMBER_NAME 
  FROM LG_MEMBER A 
   , LG_DEVICE_STATE_LOG B 
WHERE A.MEMBER_ID = B.MEMBER_ID(+) 
 AND B.LOG_ID IS NULL ; 


-- 집합연산자 개념 활용 

SELECT 회원ID 
  FROM 회원 
MINUS 
SELECT 회원ID 
  FROM 회원연락처; 
  
SELECT MEMBER_ID 
  FROM LG_MEMBER 
 MINUS 
SELECT DISTINCT MEMBER_ID 
  FROM LG_DEVICE_STATE_LOG ; 
  
--NOT EXISTS 서브쿼리를 활용 방식 
SELECT * 
  FROM LG_MEMBER A 
WHERE NOT EXISTS ( 
                    SELECT 1 
                     FROM LG_DEVICE_STATE_LOG  
                     WHERE MEMBER_ID = A.MEMBER_ID 
) ;


--ANSI JOIN 방식
SELECT A.MEMBER_NAME 
     , A.BIRTH_YEAR
     , A.CITY_NAME
     , B.DEVICE_ID 
     , B.ASSIGNED_FROM 
  FROM LG_MEMBER A INNER JOIN LG_MEMBER_DEVICE B 
    ON ( A.MEMBER_ID = B.MEMBER_ID) ; 
    
SELECT A.MEMBER_NAME 
     , A.BIRTH_YEAR
     , A.CITY_NAME
     , B.DEVICE_ID 
     , B.ASSIGNED_FROM 
  FROM LG_MEMBER A LEFT OUTER JOIN LG_MEMBER_DEVICE B
   ON (A.MEMBER_ID  = B.MEMBER_ID) ; 

SELECT A.MEMBER_NAME 
     , A.BIRTH_YEAR
     , A.CITY_NAME
     , B.DEVICE_ID 
     , B.ASSIGNED_FROM 
  FROM LG_MEMBER A OUTER JOIN LG_MEMBER_DEVICE B
   ON (A.MEMBER_ID = B.MEMBER_ID) 
WHERE B.DEVICE_ID IS NULL ; 

SELECT A.MEMBER_NAME
  FROM LG_MEMBER A LEFT OUTER JOIN LG_DEVICE_STATE_LOG B 
   ON (A.MEMBER_ID = B.MEMBER_ID) 
WHERE B.LOG_ID IS NULL ; 

---GROUP BY---


DROP TABLE 성적표 ; 
DROP TABLE 수강생정보 ; 

CREATE TABLE 수강생정보 (
학생ID VARCHAR2(9) PRIMARY KEY , 
학생이름 VARCHAR2(50) NOT NULL , 
소속반 VARCHAR2(5) 
); 

CREATE TABLE 성적표 ( 
    학생ID VARCHAR2(9) , 
    과목   VARCHAR2(30) , 
    성적   NUMBER  , 
    CONSTRAINT PK_성적표 PRIMARY KEY(학생ID , 과목) , 
    CONSTRAINT FK_성적표 FOREIGN KEY(학생ID) REFERENCES 수강생정보(학생ID) 
)  ; 

INSERT INTO 수강생정보 VALUES ('S0001' , '김현철' , 'A') ; 
INSERT INTO 수강생정보 VALUES ('S0002' , '문현중' , 'A') ; 
INSERT INTO 수강생정보 VALUES ('S0003' , '강문치' , 'B') ; 
INSERT INTO 수강생정보 VALUES ('S0004' , '박나선' , 'B') ; 
INSERT INTO 수강생정보 VALUES ('S0005' , '신태강' , 'B') ; 
INSERT INTO 수강생정보 VALUES ('S0006' , '물고기' , 'C') ; 
INSERT INTO 수강생정보 VALUES ('S0007' , '자라니' , 'C') ; 
INSERT INTO 수강생정보 VALUES ('S0008' , '공팔두' , 'C') ; 
INSERT INTO 수강생정보 VALUES ('S0009' , '최팔현' , 'C') ; 

INSERT INTO 성적표 VALUES('S0001'  ,'국어' , 90); 
INSERT INTO 성적표 VALUES('S0001'  ,'수학' , 85); 
INSERT INTO 성적표 VALUES('S0001'  ,'영어' , 100); 
INSERT INTO 성적표 VALUES('S0002'  ,'국어' , 100); 
INSERT INTO 성적표 VALUES('S0002'  ,'수학' , 100); 
INSERT INTO 성적표 VALUES('S0002'  ,'영어' , 20); 
INSERT INTO 성적표 VALUES('S0003'  ,'국어' , 100); 
INSERT INTO 성적표 VALUES('S0003'  ,'수학' , 100); 
INSERT INTO 성적표 VALUES('S0003'  ,'영어' , 20); 
INSERT INTO 성적표 VALUES('S0004'  ,'국어' , 85); 
INSERT INTO 성적표 VALUES('S0004'  ,'수학' , 40); 
INSERT INTO 성적표 VALUES('S0004'  ,'영어' , 60); 
INSERT INTO 성적표 VALUES('S0005'  ,'국어' , 100); 
INSERT INTO 성적표 VALUES('S0005'  ,'수학' , 100); 
INSERT INTO 성적표 VALUES('S0005'  ,'영어' , 100); 
INSERT INTO 성적표 VALUES ( 'S0006' , '국어' , NULL ) ; 
INSERT INTO 성적표 VALUES ( 'S0006' , '수학' , 80 ) ; 
INSERT INTO 성적표 VALUES ( 'S0006' , '영어' , NULL ) ; 

COMMIT; 

SELECT * FROM 성적표 ;
SELECT * FROM 수강생정보 ;

SELECT 소속반, COUNT(*) AS 반별인원수 
  FROM 수강생정보
GROUP BY 소속반; 

SELECT 소속반, COUNT(학생이름)
  FROM 수강생정보
GROUP BY 소속반;


SELECT 학생ID, COUNT(*), COUNT(성적) 
 FROM 성적표 
 GROUP BY 학생 ID ; 
 
SELECT * FROM 성적표 ; 

--COUNT 함수 
SELECT PRODUCT_ID 
    COUNT(*) AS 리뷰건수
 FROM PRODUCT_REVIEW
GROUP BY PRODUCT_ID ; 

SELECT HOUSEHOLD_TYPE
    , COUNT(*) AS 회원수 
    FROM LG_MEMBER
GROUP BY HOUSEHOLD_TYPE ; 

--MAX, MIN 함수 
SELECT 학생ID, MAX(성적), MIN(성적) 
  FROM 성적표 
GROUP BY 학생ID ; 

SELECT PRODUCT_ID 
    , MIN(CREATED_AT) AS 첫리뷰일 
    , MAX(CREATED_AT) AS 최근리뷰일 
 FROM PRODUCT_REVIEW 
 GROUP BY PRODUCT_ID ;
 
SELECT DEPT_NO 
    , MIN(HIRE_DATE) AS 가장빠른입사일
    , MAX(HIRE_DATE) AS 가장늦은입사일 
  FROM EMP 
GROUP BY DEPT_NO ; 

--AVG 
SELECT PRODUCT_ID
    , ROUND(AVG(RATING), 2) AS 평균평점 
 FROM PRODUCT_REVIEW
 GROUP BY PRODUCT_ID;
 
SELECT PRODUCT_ID 
    , ROUND(AVG(USE_AMOUNT_KWH), 3) AS 평균일사용량 
  FROM LG_ENERGY_USAGE_DAILY_FACT
 GROUP BY PRODUCT_ID ; 
 
SELECT TO_CHAR(GENERATED_AT, 'YYYYMMDD') AS 일자 
    , ROUND(AVG(USE_AMOUNT_KWH), 3) AS  평균일사용량 
 FROM LG_ENERGY_USAGE_DAILY_FACT 
 GROUP BY TO_CHAR(GENERATED_AT, 'YYYYMMDD') ; 

SELECT * FROM PRODUCT_REVIEW ; 

SELECT TO_CHAR(CREATED_AT, 'YYYY'), COUNT(*)
  FROM PRODUCT_REVIEW
 GROUP BY TO_CHAR(CREATED_AT, 'YYYY') ; 
 
 SELECT TO_CHAR(CREATED_AT, 'YYYY') AS 연도 
    , PRODUCT_ID 
    , COUNT(*) AS 연도별리뷰수 
   FROM PRODUCT_REVIEW
 GROUP BY TO_CHAR(CREATED_AT, 'YYYY') , PRODUCT_ID
 ORDER BY 연도 ASC, PRODUCT_ID ASC ; 
 
 SELECT CATEGORY_NAME 
    , SUM(STOCK_QTY) AS 총재고수량 
  FROM LG_PRODUCT 
GROUP BY CATEGORY_NAME ; 

SELECT MEMBER_ID 
    , SUM(USE_AMOUNT_KWH) AS 총전력사용량 
  FROM LG_ENERGY_USAGE_DAILY_FACT 
GROUP BY MEMBER_ID ;

--실습 1 
SELECT B.DEPT_NAME 
    , COUNT(*) AS 부서별사원수 
  FROM EMP A
    INNER JOIN DEPT B
     ON A.DEPT_NO = B.DEPT_NO 
WHERE A.RETIRE_YN = 'N' 
GROUP BY B.DEPT_NAME ;

SELECT DEPT NO 
    , ( 
        SELECT DEPT_NAME 
        FROM DEPT 
        WHERE DEPT_NO = EMP.DEPT_NO 
    ) AS DEPT_NAME 
    , COUNT(*) AS  부서별재직자수 
  FROM EMP 
WHERE RETIRE_YN = 'N'
 GROUP BY DEPT_NO ; 
 
 
--실습 2 
SELECT B.DEPT_NAME
    , B.GENDER
    , COUNT(*) AS 부서별사원수 
  FROM EMP A
   INNER JOIN DEPT B
    ON A.DEPT_NO = B.DEPT_NO 
WHERE A.RETIRE_YN = 'N' 
GROUP BY B.DEPT_NAME, B.GENDER ; 

--실습 3 
SELECT RETIRE_YN 
    ,COUNT(*) AS 사람수 
  FROM EMP 
GROUP BY RETIRE_YN ;  


SELECT CASE WHEN RETIRE_YN = 'Y' THEN '퇴사자' 
        ELSE '재직자'
        END AS RETIRE_YN 
        , COUNT(*) AS 사람수 
  FROM EMP 
 GROUP BY RETIRE_YN ;
 
 
--실습 4 
SELECT PRODUCT_ID 
    , COUNT(*) AS 리뷰건수 
    , ROUND(AVG(RATING), 2) AS 평균평점 
    , MIN(CREATED_AT) AS 첫리뷰일 
    , MAX(CREATED_AT) AS 최근리뷰일 
  FROM PRODUCT_REVIEW 
GROUP BY PRODUCT_ID ;

--실습 4-1 
SELECT PRODUCT_ID 
    , COUNT(*) AS 리뷰건수 
    , ROUND(AVG(RATING), 2) AS 평균평점 
    , MIN(CREATED_AT) AS 첫리뷰일 
    , MAX(CREATED_AT) AS 최근리뷰일
    , MAX(CREATED_AT) - MIN(CREATED_AT) AS 리뷰가등록된일수 
    , ROUND(COUNT(*) / (MAX(CREATED_AT) - MIN(CREATED_AT)), 1) AS 일평균리뷰건수 
  FROM PRODUCT_REVIEW 
GROUP BY PRODUCT_ID ;


--실습 5 
SELECT ERROR_CODE 
    ,COUNT(*) AS 오류발생건수 
  FROM LG_DEVICE_STATE_FACT 
WHERE ERROR_CODE IS NOT NULL 
  AND ERROR_CODE != '0000' 
GROUP BY ERROR_CODE ;


--실습 6 
SELECT PRODUCT_ID
    ,SUM(USE_AMOUNT_KWH) AS 총전력사용량 
    ,ROUND(AVG(USE_AMOUNT_KWH), 3) AS 평균일사용량
  FROM LG_ENERGY_USAGE_DAILY_FACT 
GROUP BY PRODUCT_ID ; 


---HAVING---
--실습 1 
SELECT B.DEPT_NAME 
    , COUNT(*) AS 부서별사원수 
  FROM EMP A
    INNER JOIN DEPT B
     ON A.DEPT_NO = B.DEPT_NO 
WHERE A.RETIRE_YN = 'N' 
GROUP BY B.DEPT_NAME 
HAVING COUNT(*) >= 10 ;

--실습2
SELECT PRODUCT_ID 
    , COUNT(*) AS 리뷰건수 
    , ROUND(AVG(RATING), 2) AS 평균평점 
    , MIN(CREATED_AT) AS 첫리뷰일 
    , MAX(CREATED_AT) AS 최근리뷰일 
  FROM PRODUCT_REVIEW 
GROUP BY PRODUCT_ID 
HAVING COUNT(*) >= 1000 ; 

--실습3 
SELECT ERROR_CODE 
    ,COUNT(*) AS 오류발생건수 
  FROM LG_DEVICE_STATE_FACT 
WHERE ERROR_CODE IS NOT NULL 
  AND ERROR_CODE != '0000' 
GROUP BY ERROR_CODE 
HAVING COUNT(*) >= 300 ; 

---ORDER BY---
SELECT * 
  FROM LG_PRODUCT
ORDER BY PRICE DESC;

SELECT PRODUCT_NAME
    , CATEGORY_NAME
    , STOCK_QTY
  FROM LG_PRODUCT
ORDER BY CATEGORY_NAME , STOCK_QTY DESC ; 



SELECT * 
  FROM EMP 
ORDER BY JOB_TITLE ; 

SELECT * 
  FROM EMP 
ORDER BY CASE WHEN JOB_TITLE = '선임' THEN 1 
              WHEN JOB_TITLE = '책임' THEN 2 
              WHEN JOB_TITLE = '팀장' THEN 3 
              WHEN JOB_TITLE = '수석' THEN 4 
            ELSE 5 
        END ; 

COMMIT;


USERS

ALTER TABLE USERS RENAME COLUMN EMALL TO EMAIL;
INSERT INTO users (ID, NAME, EMAIL) VALUES (1, 'Alice', 'alice@example.com');

SELECT * FROM USERS ;
INSERT INTO users (id, name, email) VALUES (2, 'Alice', 'alice@example.com');

[TEST] 
INSERT INTO users (id, name, email) VALUES ('AA' , 'Alice', 'alice@example.com');


UPDATE USERS 
    SET NAME = '이름변경'
      , EMAIL = '메일변경@naver.com'
  WHERE ID = 1 ; 
  
  
  
--문제1 
SELECT DEPT_NO 
    FROM DEPT
WHERE DEPT_NAME LIKE '%전장%';


EMP_ID : 'EMP101' 
	NAME : '김연경' 
	GENDER : 'F' 
	BIRTH_DATE : '19801212'
	HIRE_DATE : '20250718'
	JOB_TITLE : '팀장'
	JOB_LEVEL : 'P1' 
	DEPT_NO : 'D003'
	LEAVE_AMOUNT : 15 
	RETIRE_YN : 'N'
	RETIRE_DATE : NULL 
	CREATED_AT : 현재시점 (SYSDATE)
    
SELECT * FROM EMP 
 WHERE EMP_ID = 'EMP101' ; 
 
 

--문제2
SELECT PRODUCT_ID 
     , PRODUCT_NAME
     , STOCK_QTY
     , DEVICE_TYPE
  FROM LG_PRODUCT 
WHERE PRODUCT_ID = 'P009' 
UPDATE LG_PRODUCT 
    SET STOCK_QTY = STOCK_QTY - 3 
WHERE PRODUCT_ID = 'P009';

COMMIT; 


--문제3
SELECT REVIEW_ID
    , PRODUCT_ID 
    , RATING 
    , REVIEW_TEXT
    , CREATED_AT 
  FROM PRODUCT_REVIEW  
WHERE LENGTH(REVIEW_TEXT) <= 10 ; 

DELETE FROM PRODUCT_REVIEW  
  WHERE LENGTH(REVIEW_TEXT) <= 10 ;
  
COMMIT ; 


--문제4
SELECT DEVICE_ID
    , DEVICE_ALIAS
    , INSTALL_ROOM 
  FROM LG_DEVICE 
WHERE DEVICE_ALIAS = 'Main Refrigerator' 

UPDATE LG_DEVICE 
    SET DEVICE_ALIAS = '주방 메인 냉장고'
      , INSTALL_ROOM = '주방' 
WHERE DEVICE_ALIAS = 'Main Refrigerator' ; 


--문제5
INSERT INTO LG_MEMBER (
    , MEMBER_ID 
    , MEMBER_NAME
    , GENDER_CODE 
    , BIRTH_YEAR 
    , CITY_NAME
    , DISTRICT_NAME
    , HOUSEHOLD_TYPE
    , HOUSEHOLD_SIZE
    , HOME_TYPE
    , HOME_AREA_M2
    , PET_FLAG
    , CHILD_FLAG 
    , OCCUPANCY_PATTERN
    , JOINED_AT 
VALUE ( 
    'MEMBER51' 
    '한지우' 
    'F'
    1998
    '서울'
    '마포구'
    'SINGLE'
    1
    'OFFICETEL' 
    33
    'N'
    'N'
    'OFFUCE_WORKER'
    현재시점 

INSERT INTO LG_DEVICE VALUE (


