SELECT ROWNUM, A.* 
  FROM MART_UNMANNED_STORE_GU_20254 A 
WHERE ROWNUM <= 5 ; 

SELECT GU_NAME 
    , TOTAL_UNMANNED_STORE_CNT 
  FROM MART_UNMANNED_STORE_GU_20254 
WHERE ROWNUM <= 5
ORDER BY TOTAL_UNMANNED_STORE_CNT DESC; 

SELECT *
  FROM (
        SELECT GU_NAME
             , TOTAL_UNMANNED_STORE_CNT
          FROM MART_UNMANNED_STORE_GU_20254
         ORDER BY TOTAL_UNMANNED_STORE_CNT DESC
       )
 WHERE ROWNUM <= 5;
 
 
 --문제2 
SELECT *
  FROM( 
SELECT GU_NAME 
    , ICECREAM_STORE_CNT 
  FROM MART_UNMANNED_STORE_GU_20254 
ORDER BY ICECREAM_STORE_CNT DESC 
    ) 
WHERE ROW
 SELECT GU_NAME 
    , icecream_store_cnt
  FROM MART_UNMANNED_STORE_GU_20254 
ORDER BY icecream_store_cnt DESC 
FETCH FIRST 5 ROWS ONLY ; 

--문제3
SELECT * 
  FROM( 
        SELECT SVC_NAME 
            , SUM(SALES_AMT) AS TOTAL_SALES_AMT
            FROM STG_SALES_GU_20254 
        GROUP BY SVC_NAME
        ORDER BY SUM(SALES_AMT) DESC
        ) 
WHERE ROWNUM <= 10 ;
  
  SELECT SVC_NAME 
    , SUM(SALES_AMT) AS TOTAL_SALES_AMT
  FROM STG_SALES_GU_20254 
 GROUP BY SVC_NAME
ORDER BY SUM(SALES_AMT) DESC 
FETCH FIRST 10 ROWS ONLY ; 

