SELECT NAME
     , RETIRE_YN
     , GENDER
    , JOB_TITLE 
    FROM EMP
 WHERE RETIRE_YN = 'N' AND GENDER = '남성' AND JOB_TITLE = '팀장'
ORDER BY NAME DESC ;
 
SELECT PRODUCT_ID 
     , REVIEW COUNT(*) AS 리뷰5점계수 
  FROM PRODUCT_REVIEW 
ORDER BY PRODUCT_ID DESC
WHERE REVIEW = 5 ; 

SELECT REVIEW_DATE AS 리뷰작성연도
    , REVIEW COUNT(*) AS 리뷰개수2점이하만
    FROM PRODUCT_REVIEW 
 ORDER BY REVIEW_DATE DESC
WHERE REVIEW_COUNT <= 2 ;


SELECT DEPT_NAME 
     , DEPT_EN_NAME
     , (SELECT COUNT(*) 
          FROM EMP
         WHERE DEPT.DEPT_NO = DEPT_NO
           AND RETIRE_YN = 'N' ) AS 부서별인원수 
  FROM DEPT ;

SELECT A.DEPT_NAME 
    ,A.DEPT_NO 
    ,B.DEPT_NAME 
    ,B.DEPT_NO
  FROM DEPT A INNER JOIN EMP B 
ORDER BY DEPT_NAME DESC
    ON A.DEPT_NAME = B.DEPT_NAME ;


SELECT * 
    FROM MEMBER_EXAM; 

CREATE TABLE MEMBER_EXAM (
    MEMBER_ID VARCHAR2(20)PRIMARY KEY
    NAME VARCHAR2(50), NOT NULL
    ID_NUMBER VARCHAR2(255)PRIMARY KEY
    JOIN_DATE DATE DEFAULT SYSDATE
); 
    
    
SELECT * FROM MEMBER_EXAM


INSERT INTO MEMBER_ID VALUES 'AAA';
INSERT INTO NAME VALUES '짱구' ;
INSERT INTO ID_NUMBER VALUES '001212-1234567' ;
INSERT INTO JOIN_DATE VALUES SYSDATE ;

ALTER TABLE MEMBER_EXAM RENAME COLNUM MEMBER_ID TO '맹구' ;
